.Dd 2024/09/07
.Dt seed 1
.Os Posix
.Sh NAME
.Nm seed,
.Nd Portable seed generator.
.Sh SYNOPSIS
.Nm seed
.Ar bits
.Sh DESCRIPTION
Gather entropy from a chaotic generator and return n 
bytes in headecimal. Ideal to supplement your entropy 
easily on all platforms.
.Pp
The chaotic generator creates an unstable complex 
system by using threads and race conditions. Entropy is 
gathered by observing the unstable system at interval.
.Pp
.Sh SEE ALSO
.Xr random 1
.Xr seedy 3
