.Dd 2024/09/07
.Dt seedy 3
.Os Posix
.Sh NAME
.Nm seedy,
.Nd Portable random number generator.
.Sh SYNOPSIS
.Nm seedy
.Ar buffer
.Ar count
.Sh DESCRIPTION
#include "seedy.h"
seedy(uint8_t* buffer, size_t bytes );
.Pp
.Ar buffer 
Pointer to an array of uint64_t values.
.Pp
.Ar bytes
Number of bytes to obtain.
.Pp
.El
.Pp
.Sh SEE ALSO
.Xr random 1
.Xr seed 1
